appName : ${applicationName}
elementsPerPage: 10
theme : org.wso2.uuf.theme.default
menu :
  main :
    Home : {link: "", icon: "fw-home"}
    Submenu :
      MenuItem1 : {link: "items"}
errorPages:
  "404": /base/error/404
  default: /base/error/default